services:
  - type: web
    name: typer-rpg-backend
    runtime: java
    buildCommand: "./gradlew clean build -x test"
    startCommand: "java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar build/libs/backend-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx512m"
      - key: SPRING_PROFILES_ACTIVE
        value: prod
